training:
  batch_size: 16
  epochs: 200
  learning_rate: 0.0001
  reg: 0.0005
  momentum: 0.9

model:
  name: SegNet
  save_best: True
  checkpoint: checkpoints/segnet.pth
  out_dir: tests/predictions

dataset:
  name: VOC2012
  path: data/voc/VOC2012
  train_data: ImageSets/Segmentation/train.txt
  validation_data: ImageSets/Segmentation/val.txt
  img_dir: JPEGImages
  mask_dir: SegmentationClass


loss:
  loss_type: CE # CE or Focal